# Generated by Django 4.2.4 on 2023-08-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=10)),
                ('event_template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEventEmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=100)),
                ('email_body', models.TextField()),
                ('email_status', models.CharField(choices=[('S', 'SUCCESS'), ('F', 'FAILURE')], max_length=1)),
                ('email_timestamp', models.DateTimeField(auto_now_add=True)),
                ('email_failure_reason', models.TextField(blank=True, null=True)),
                ('employee_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_data.employeeevents')),
            ],
        ),
    ]
