# Generated by Django 4.2.4 on 2023-08-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeventemailhistory',
            name='error_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeventemailhistory',
            name='email_status',
            field=models.CharField(choices=[('S', 'SUCCESS'), ('F', 'FAILURE'), ('N', 'NO EVENT')], max_length=1),
        ),
    ]
