# Generated by Django 4.2.4 on 2023-08-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0002_employeeevents_event_month'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeevents',
            unique_together={('employee', 'event_type')},
        ),
    ]
